<a href="https://colab.research.google.com/github/Renmsd/portfoilo/blob/main/Gen%20Ai/Neural%20Network/DL_NN_2_PyTorch_Tensor_Basics_(demo_).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://s3.amazonaws.com/weclouddata/images/logos/wcd_logo_new_2.png" width="10%">
<h1><center>Pytorch Basics</center></h1>

## Tensor Basics

### Tensor and dimension of tensor

Tensor is thought of generalization of scalars, vectors, and matrices to higher dimensions.

**0-D tensor**: A scalar (just a single number), for example: `1`

**1-D tensor**: A vector (like a list of numbers), for example: `[1, 2, 3]`

**2-D tensor**: A matrix (like a 2D grid of numbers), for example:
```
[
 [1,2,3],
 [4,5,6]
]
```

**3-D tensor and higher**: Higher-dimensional arrays or tensors. Here is an exmaple for 3-D tensor:
```
[
 [
  [1,2,3],
  [4,5,6]
 ],
 [
  [9,8,7],
  [6,5,4]
 ]
]
```
<img src="https://miro.medium.com/v2/resize:fit:1400/1*pgVlfgFbk3t3FWe3QEVlXA.png" alt="Markdown Monster icon" width="30%" />

More visually:

0-D tensor (Scalar) is like a single point.

1-D tensor (Vector) is like a line with multiple points.

2-D tensor (Matrix) is like a grid or a table. Imagine a spreadsheet or a checkerboard.

3-D tensor is like a cube or box.

4-D tensor is like a series of cubes



### Tensor Dimensions in NLP and Computer Vision Tasks

Here are some sample use cases for multiple dimension tensor in NLP(Natural Language Processing) and CV(Computer Vision)

<br />

#### NLP
**1. Word Embeddings**:
 - Single Word:
   - 1-D tensor(vector): If you embed a single word using, for instance, a 300-dimensional embedding, you get a vector of size **`[embedding_dimension]`**.
     - Example: "cat" → `[0.12, -0.25, ... , 0.45]` (assuming 300 elements in total)
 - Squence of words:
   - 2-D tensors(matrix): If you have a sequence of words and represent each word by an embedding vector, the data can be represented as a matrix of size **`[sequence_length, embedding_dimension]`**.

<br />

**2. Batch of Sequences**:

 - 3-D tensors: When processing multiple sequences in a batch, it's common to have a tensor of shape **`[batch_size, sequence_length, embedding_dimension]`**.

 <br />

**3. Recurrent Neural Networks (RNNs)**:

 - 3-D tensors: RNNs often operate on 3-D tensors where dimensions can represent **`[batch_size, sequence_length, features]`**.

 <br />

**4. Transformer Architectures (like BERT)**:

 - 3-D tensors: Similar to RNNs, the input and intermediate representations are often 3-D tensors, e.g., **`[batch_size, sequence_length, embedding_dimension]`**.

 <br />

**5. One-Hot Encoded Text**:

 - One-hot encoding represents words (or characters) as vectors where all positions are zero, except for the position corresponding to the word, which is set to 1.

 - Single Word:
   - Vector (1-D tensor): For a vocabulary of size `V`, a word's one-hot representation would be a vector of size `[V]`, with one element set to 1, and all others set to 0.
     - Example: For a vocabulary `{"the", "black", "cat"}`, the word "cat" might be represented as `[0, 0, 1]`.
 - Sequence of Words:
   - Matrix (2-D tensor): For a sequence of n words, you'd stack the one-hot vectors, leading to a size of **`[sequence_length, V]`**.
     - Example: "The black cat" → matrix of size `(3, 3)`, with each row being the one-hot representation of a word.
     
<br />

**6. Document Embeddings**:
 - Single Document:
   - Vector (1-D tensor): A document embedded into a fixed-size vector, e.g., 500-dimensional, would have size `[embedding_dimension]`.
     - Example: The entire text of "The quick brown fox jumps over the lazy dog" is transformed into a vector like `[0.45, -0.12, ... , 0.58]` (assuming 500 elements).
 - Batch of Documents:
   - Matrix (2-D tensor): For a batch of `m` documents, where each document is represented as a fixed-size vector (e.g., 500-dimensional), you'd have a matrix of size **`[batch_size, embedding_dimension]`**.
     - Example: If you're processing 10 documents at once, each with a 500-dimensional embedding, the tensor shape would be `(10, 500)`.
     
<br />

#### CV
**1. Images**:
 - 3-D tensors: Common for individual images. Dimensions usually represent **`[height, width, channels]`** where channels are often RGB (3 channels). For grayscale images, the dimension might be just **`[height, width, 1]`**.
 - In Pytorch, the shape is `[channels, height, width]`

<br />

**2.Batches of Images**:
 - 4-D tensors: When processing multiple images in a batch, another dimension is added. For example, **`[batch_size, height, width, channels]`**.
 - In Pytorch, the shape is `[batch_size, channels, height, width]`

<br />

**3.Convolutional Neural Networks**:
- 4-D tensors: Convolutional layers in deep learning models often operate on 4-D tensors, especially when using mini-batch training. Intermediate layers can produce tensors of varying spatial dimensions depending on the layer's operations (e.g., convolution, pooling).

### Create Tensor in Code

In [ ]:
import torch
import numpy as np

#### Create from Numpy Array

In [ ]:
# create a numpy array
num = [1,2,3,4,5,6]
arr = np.array(num)

print(num)
print(arr)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [ ]:
# check the data type and arr type


In [ ]:
# convert numpy array to tensor
my_tensor = torch.from_numpy(arr)

In [ ]:
#type(my_tensor)
type(my_tensor)

torch.Tensor

In [ ]:
# convert 2d array to tensor
arr2d = np.arange(0.0, 12.0)
arr2d = arr2d.reshape(4, 3)
arr2d
# print(torch.tensor(arr2d))
torch.from_numpy(arr2d)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [ ]:
# Create a 1D array with values from 0.0 up to (but not including) 9.0
# Display the array
arr = np.arange(0.0, 9.0,1)
# torch.from_numpy(arrz)
torch.tensor(arr)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [ ]:
# Reshape the 1D array into a 3x3 2D array (matrix)
# Display the reshaped array
arr2d = arrz.reshape(3, 3)
arr2d

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
# Convert the NumPy 2D array into a PyTorch tensor

# Display the created tensor


In [ ]:
# another way to convert the numpy array to tensor


The different between `torch.from_numpy` and `torch.as_tensor` is that:
 - Data Type Support
   - `torch.from_numpy` only accepts numpy arrays.
   - `torch.as_tensor` is more versatile. It can accept a wider range of data types, including numpy arrays, Python lists, scalar values, and other tensor-like objects.
 -  Dtype and Device Handling
    - `torch.from_numpy` does not allow you to specify the dtype or device; the returned tensor's properties are inferred from the numpy array.
    - `torch.as_tensor` provides more flexibility. You can use the dtype and device arguments to specify the desired data type and device (e.g., CPU or GPU) for the created tensor.

In [ ]:
# The code below will give you the TypeError: expected np.ndarray (got list)
# torch.from_numpy([1, 2, 3])

In [ ]:
# But it works with torch.as_tensor, since it support more data types
#torch.as_tensor([1, 2, 3])

from the document of `torch.from_numpy`, we can see it only take one parameter, which is `ndarray`

In [ ]:
help(torch.from_numpy)

But in the document of `torch.as_tensor`, it also takes dtype and device

In [ ]:
help(torch.as_tensor)

In [ ]:
arr.dtype

In [ ]:
if torch.cuda.is_available():
    my_tensor3 =torch.as_tensor(arrz, device="cuda :0")
    print(my_tensor3)

In [ ]:
# my_tensor2 are the tensor directly convert from the numpy arrau in our previous code

#your code
my_tensor2 = torch.as_tensor(arrz)
my_tensor2
# arrz = np.arange(0.0, 9.0,1)
# # torch.from_numpy(arrz)
# torch.tensor(arrz)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [ ]:
# Create a tensor from NumPy array with integer data type (int64)
my_tensor2.type(torch.int64)
# Create another tensor from the same array with float data type (float64)

# Print the integer tensor
print(my_tensor2.dtype)
# Print the data type of the integer tensor

# Print the float tensor


torch.float64


In [ ]:
# use gpu with torch.as_tensor
#your code

Both `torch.from_numpy` and `torch.as_tensor` share the same memory as numpy array, which means that it just creates a link to the numpy array, and if the value changes in the array, the value of the tensor will change as well, verse versa.

In [ ]:
# my_tensor is created by torch.from_numpy from arr
# my_tensor2 is create by torch.as_tensor from arr
print("original numpy array\t\t\t", arr)
print("tensor created by torch.from_numpy:\t", my_tensor)
print("tensor created by torch.as_tensor:\t", my_tensor2)

original numpy array			 [1 2 3 4 5 6]
tensor created by torch.from_numpy:	 tensor([1, 2, 3, 4, 5, 6])
tensor created by torch.as_tensor:	 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)


In [ ]:
arr[0] = 100
print("original numpy array\t\t\t", arr)
print("tensor created by torch.from_numpy:\t", my_tensor)
print("tensor created by torch.as_tensor:\t", my_tensor2)

original numpy array			 [100   2   3   4   5   6]
tensor created by torch.from_numpy:	 tensor([100,   2,   3,   4,   5,   6])
tensor created by torch.as_tensor:	 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)


In [ ]:
my_tensor[1] = 88
print("original numpy array\t\t\t", arr)
print("tensor created by torch.from_numpy:\t", my_tensor)
print("tensor created by torch.as_tensor:\t", my_tensor2)

original numpy array			 [100  88   3   4   5   6]
tensor created by torch.from_numpy:	 tensor([100,  88,   3,   4,   5,   6])
tensor created by torch.as_tensor:	 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)


In [ ]:
my_tensor2[3] = 66
print("original numpy array\t\t\t", arr)
print("tensor created by torch.from_numpy:\t", my_tensor)
print("tensor created by torch.as_tensor:\t", my_tensor2)

original numpy array			 [100  88   3   4   5   6]
tensor created by torch.from_numpy:	 tensor([100,  88,   3,   4,   5,   6])
tensor created by torch.as_tensor:	 tensor([ 0.,  1.,  2., 66.,  4.,  5.,  6.,  7.,  8.], dtype=torch.float64)


However, `torch.as_tensor` ***only*** share the memory when the input is numpy array. If it takes other data types as input, it won't share the memory.

For example:

In [ ]:
my_ls = [1,2,3]
my_tensor_from_ls = torch.as_tensor(my_ls)
print("original list\t\t\t\t\t", my_ls)
print("tensor created by torch.as_tensor from list:\t", my_tensor_from_ls)

my_ls[0] = 99
print("After change the list")
print("original list\t\t\t\t\t", my_ls)
print("tensor created by torch.as_tensor from list:\t", my_tensor_from_ls)

In [ ]:
my_val = 10
my_tensor_from_val = torch.as_tensor(my_val)
print("original value\t\t\t\t\t\t", my_val)
print("tensor created by torch.as_tensor from scalar value:\t", my_tensor_from_val)

my_val = 99
print("After change the value")
print("original value\t\t\t\t\t\t", my_val)
print("tensor created by torch.as_tensor from scalar value:\t", my_tensor_from_val)

If we **don't** want them to create the direct link and share the memory with numpy array, we just need a copy of the data, we can use `torch.tensor` or `torch.Tensor`

In [ ]:
# create a new array
new_arr = np.arange(0, 6)


# create tensor using torch.tensor
new_tensor = torch.tensor(new_arr)
# create tensor using torch.Tensor
new_Tensor = torch.Tensor(new_arr)
# create tensor using torch.from_numpy
new_tensor_from_np = torch.from_numpy(new_arr)

# create tensor using torch.from_numpy


# Print the original NumPy array
print(new_tensor)
# Print the tensor created using torch.from_numpy (shares memory with NumPy array)
print(new_Tensor)
# Print the tensor created using torch.tensor (creates a copy of data)
print(new_tensor_from_np)
# Print the tensor created using torch.Tensor (uninitialized if no data is given, but here it copies data)


tensor([0, 1, 2, 3, 4, 5])
tensor([0., 1., 2., 3., 4., 5.])
tensor([0, 1, 2, 3, 4, 5])


In [ ]:
# Modify the first element of the original NumPy array

# Print the modified NumPy array

# Print the tensor created using torch.from_numpy (will also reflect the change, since it shares memory)

# Print the tensor created using torch.tensor (will NOT change, since it makes a copy)

# Print the tensor created using torch.Tensor (also does NOT change, since it makes a copy)


In [ ]:
# Change the 4th element (index 3) of the original NumPy array

# Print the modified NumPy array

# Print the tensor created using torch.from_numpy (will reflect the change due to shared memory)

# Print the tensor created using torch.tensor (remains unchanged, copy made earlier)

# Print the tensor created using torch.Tensor (remains unchanged, copy made earlier)


So there are no memory sharing between the original numpy array and the tensor created by the `torch.tensor`.

The difference between `torch.tensor` and `torch.Tensor` is that, `torch.Tensor` is actually an alias for the default tensor type in PyTorch, which is `torch.FloatTensor`, which mean the dtype of tensor create by `torch.Tensor` is always `torch.float32`. But with `torch.tensor`, we can still assign the dtype.

In [ ]:
print(new_Tensor.dtype)
print(new_tensor.dtype)

In [ ]:
# Create a new tensor from the NumPy array with explicit int64 data type

# Print the data type of the new tensor


In summary, these are the methods we can use to create the tensor from the numpy array:

<br />

| Method          | Acceptable Inputs              | Assignable `dtype` | Memory Sharing with numpy | Default `dtype` (if not assigned) |
|-----------------|-------------------------------|--------------------|---------------------------|----------------------------------|
| `torch.from_numpy` | Numpy arrays only            | No                 | Yes                       | Inferred from numpy array        |
| `torch.as_tensor`  | Numpy arrays, lists, etc.    | Yes                | Yes (only with numpy & no dtype conversion) | Inferred from input            |
| `torch.tensor`     | Numpy arrays, lists, etc.    | Yes                | No                        | Inferred from input              |
| `torch.Tensor`     | Numpy arrays, lists, etc.    | No                 | No                        | `torch.float32`                  |


#### Create Directly

Instead of convert numpy array to tensor, we can also create tendsor from scratch

`torch.empty` is used to allocate uninitialized memory for a tensor. The values that occupy the uninitialized memory can be arbitrary and should not be relied upon without first setting or initializing them in some manner. We can regard this as a placeholder for the memory.


In [ ]:
#your code

Using the values from torch.empty without initialization can lead to unexpected behaviors, as the values are arbitrary.

If we want to create a tensor with specific initial values (like zeros or ones), you would use functions like `torch.zeros` or `torch.ones` respectively.

In [ ]:
# Create a 2x2 tensor filled with zeros

# Create a 3x4x5 tensor (3D tensor) filled with zeros


In [ ]:
# Create a 2x2 tensor filled with ones

# Create a 3x4x5 tensor (3D tensor) filled with ones


We can also use the function like `torch.arange` to create a range of vector, similary to the numpy array

In [ ]:
#your code

In [ ]:
             #start, #end,  #step
#torch.arange(0,     10,     1)

In [ ]:
#torch.arange(0, 20, 2)

And we can use reshape to reshape the above 1D tensor, similary to the numpy array

In [ ]:
#np.arange(0, 16).reshape(4, 4)

In [ ]:
#torch.arange(0, 12, 1).reshape(3, 4)

Or we can also use the `linspace`, which returns a 1-dimensional tensor of evenly spaced values between two specified start and end values. Similar to the numpy.

In [ ]:
#your code

In [ ]:
#your code

We can use `torch.rand`, `torch.randn` and `torch.randint` to generate tensor with random value.

`torch.rand`: Generates a tensor filled with random numbers uniformly distributed between `0` and `1`.

`torch.randn`: Generates a tensor filled with random numbers from a standard normal distribution (mean = 0 and variance = 1).

`torch.randint`:  a tensor filled with random integers between `low`(inclusive) and `high`(exclusive). If only one value is provided, it assumes between 0 and that value.

In [ ]:
#your code

In [ ]:
#your code

In [ ]:
              #low  #high   #size
#torch.randint(0,    10,    (2, 2))

Since we are generating the random value here, similar to `numpy.random.seed()` method, PyTorch also have a method called `torch.manual_seed()`, which is used to set the random seed for generating deterministic random numbers, ensuring reproducibility across runs.

Reproducibility is crucial in many areas, especially in scientific experiments, machine learning, and data analysis. By using a consistent seed value for random number generation, researchers and practitioners can ensure that the randomness introduced in their experiments is consistent every time they run them. This makes experiments replicable and results comparable.

In [ ]:
#your code

Please note that, for reproducibility in interactive environments like Jupyter Notebooks, it's advisable to set the random seed using `torch.manual_seed()` and immediately generate random numbers **within the same cell**. This practice ensures consistent results every time the cell is executed, guarding against potential inconsistencies that might arise from executing cells out of order or intervening operations that use the random number generator.

Until now, we can see for PyTorch, most of the methods to generate value are similar to numpy, so if you are familiar with numpy, you can get on this easily.

In PyTorch, we can also use the `*_like` methods to create tensors with the **same shape**(and, optionally, data type) as a given tensor. These methods are convenient when you want a new tensor that matches the dimensions of an existing tensor but initialized differently.

Here are the examples:

In [ ]:
# give an example of 3D tensor
my_3dtensor = torch.ones(7,1)

In [ ]:
my_3dtensor.shape

torch.Size([2, 1])

In [ ]:
my_3dtensor.dtype

torch.float32

In [ ]:
print("torch.empty_like")
print(torch.empty_like(my_3dtensor))
print("="*80)
print("torch.zeros_like")
print(torch.zeros_like(my_3dtensor))
print("="*80)
print("torch.ones_like")
print(torch.ones_like(my_3dtensor))
print("="*80)
print("torch.randint_like")
print(torch.randint_like(my_3dtensor, low=0, high=10))

torch.empty_like
tensor([[8.1603e-24],
        [0.0000e+00],
        [0.0000e+00],
        [1.4013e-45],
        [0.0000e+00],
        [0.0000e+00],
        [6.8664e-44]])
torch.zeros_like
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
torch.ones_like
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])
torch.randint_like
tensor([[0.],
        [7.],
        [1.],
        [8.],
        [0.],
        [7.],
        [3.]])


BUT note that if we run `torch.rand_like` and `torch.randn_like` on this example, we will get the data type issue. The function `torch.rand_like()` tries to fill a tensor with random numbers from a uniform distribution in the range `[0, 1)` and `torch.randn_like()` tries to fill with random numbers drawn from a standard normal distribution (with mean 0 and standard deviation 1). This operation requires a **floating-point data type**, but our `my_3dtensor` is **`int64`**.

To avoid the error, we can convert the `my_3dtensor` to a floating-point type

In [ ]:
# convert to float-point type
#your code
my_3dtensor_float = my_3dtensor.type(torch.float32)
print("torch.rand_like")
print(torch.rand_like(my_3dtensor_float))
print("="*80)
print("torch.randn_like")
print(torch.randn_like(my_3dtensor_float))

torch.rand_like
tensor([[0.6810],
        [0.2370],
        [0.7508],
        [0.5054],
        [0.0073],
        [0.8836],
        [0.4782]])
torch.randn_like
tensor([[-0.5484],
        [ 1.5349],
        [ 0.2008],
        [ 0.7759],
        [ 0.5869],
        [-0.2893],
        [-0.9562]])


However, `torch.randint_like` doesn't have restrictions on the source dtype, it will produce a tensor with the same data type as the source tensor, even if the generated values are integers

In [ ]:
my_float_tensor = #your code
print(my_float_tensor)
print(my_float_tensor.dtype)

In [ ]:
my_generate_tensor = #your code
my_generate_tensor

In [ ]:
#my_generate_tensor.dtype

Here is the summary of the `*_like` methods:

<br />

| Method                      | Description                                                           | Requires Source `dtype`   | Output `dtype`                  |
|-----------------------------|-----------------------------------------------------------------------|---------------------------|--------------------------------|
| `torch.empty_like(tensor)`  | Generates an uninitialized tensor.                                    | Any                       | Matches source tensor          |
| `torch.zeros_like(tensor)`  | Generates a tensor filled with zeros.                                 | Any                       | Matches source tensor          |
| `torch.ones_like(tensor)`   | Generates a tensor filled with ones.                                  | Any                       | Matches source tensor          |
| `torch.rand_like(tensor)`   | Generates uniform random numbers between 0 and 1.                     | Floating-point            | Matches source tensor          |
| `torch.randn_like(tensor)`  | Generates random numbers from a standard normal distribution.         | Floating-point            | Matches source tensor          |
| `torch.randint_like(tensor, low, high)` | Generates random integers between `low` and `high` (exclusive). | Any                       | Matches source tensor, but filled with integers |



There are another two methods you may need to use to create the tensor:

`torch.full` - It creates a tensor of size size with all values set to fill_value.

`torch.eye` - It creates a 2-D tensor with ones on the diagonal and zeros elsewhere, essentially an identity matrix.

In [ ]:
#your code

In [ ]:
#your code

In additional, all the `torch.*` method we metioned here supports the GPU computation.

## Tensor Properties and Operations

### Tensor Properties

There are several properties that you can leverage to better understand and work with them.


 - `dtype`: The data type of a tensor tells us the type of data contained in it, such as integers or floats.

 - `shape`: The shape of a tensor provides the dimensions of the tensor.

 - `size()`: The `size()` method returns the shape of the tensor. It's an alternative to `shape`.

 - `dim()`: This tells you the number of dimensions present in the tensor.

 - `max()/min()`: Get the maximum or minimum value from the tensor.

In [ ]:
# dtype

# Create a tensor with float values

# Print the data type of the float tensor

# Create a tensor with integer values

# Print the data type of the integer tensor


In [ ]:
# Create a 2D tensor (matrix) with 3 rows and 2 columns

# Create a 3D tensor (2 matrices, each of size 2x2)

# Print the 2D tensor

# Print a separator line for clarity

# Print the 3D tensor


In [ ]:
# shape
print(f"Shape of tensor_2d: {tensor_2d.shape}")
print(f"Shape of tensor_3d: {tensor_3d.shape}")

In [ ]:
# size()
print(f"Size of tensor_2d: {tensor_2d.size()}")
print(f"Size of tensor_3d: {tensor_3d.size()}")

In [ ]:
# dim()
print(f"Dimensions of tensor_2d: {tensor_2d.dim()}")
print(f"Dimensions of tensor_3d: {tensor_3d.dim()}")

In [ ]:
# min/max
print(f"Max value: {tensor_3d.max()}")
print(f"Min value: {tensor_3d.min()}")

### Tensor Indexing and Slicing
Tensor indexing and slicing is a way to access or modify specific portions of a tensor. It's similar to Python list indexing with some added functionalities to cater to multi-dimensional data.

#### Indexing

The basic indexing is similar to the python list or numpy array. we can either indexing a single item or use the negative indexing

In [ ]:
tensor1d = torch.tensor([0, 1, 2, 3, 4])

# Indexing a single item


# Negative indexing



In [ ]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(tensor2d)
print()
# Accessing a specific row
#your code
  # Outputs: [4, 5, 6]

# Accessing a specific element
#your code  # Outputs: 6

In [ ]:
tensor3d = torch.tensor([
                         [[ 0,  1,  2,  3], [ 4,  5,  6,  7]],
                         [[ 8,  9, 10, 11], [12, 13, 14, 15]],
                         [[16, 17, 18, 19], [20, 21, 22, 23]]
                        ])

print(tensor3d)

# Access the first batch
#your code

# Access the second element of the first batch
#your code

# Access the third element of the second column of the second batch
#your code
# Extract a subarray from the third batch
#your code

#### Slicing

Slicing in tensors allows us to extract continuous segments, akin to subsetting lists or arrays in Python, enabling precise and flexible data partitioning.

In [ ]:
# Create a simple 1D tensor with values 0 to 4

# Slice from index 1 to 3 (end index 4 is exclusive) → gives [1, 2, 3]

# Slice from index 1 to 3 with step size 2 → picks every second element → gives [1, 3]


In [ ]:
# Create a 2D tensor (matrix) with 3 rows and 2 columns

# Create a 3D tensor (2 matrices, each of size 2x2)


In [ ]:
print(f"The 2D tensor \n{tensor_2d}")
print("="*40)

# Selecting the row for 2d tensor


# Selecting the column for 2d tensor


# Selecting multiple rows


In [ ]:
print(f"The 3D tensor \n{tensor_3d}")
print("="*40)

# Selecting a 2D matrix from 3d tensor


# Selecting a row across matrices


# Selecting a column across matrices


# Selecting a single value


# Selecting a sub-tensor



The `:` here in the `[:, :, 0]` is just a placeholder, that signifies **"take everything along this dimension."** It is used for slicing to specify that all elements along a given dimension should be included. This is very much like the behavior of slicing in Python lists and NumPy arrays.

And in the *Selecting the first row across all matrices* example, the `[:, 0]` is equal to `[:, 0, :]`. In PyTorch (as well as in NumPy), when you're slicing into multi-dimensional arrays, if you don't provide indices for all the dimensions, the missing dimensions are considered as complete slices (`:`).

#### Use Cases with Real-world Scenarios

1. Extracting the First Token's Embedding in BERT

    In transformers like BERT, the embedding of the first token (often `[CLS]`) is typically used as the aggregate sequence representation.

    For example, we want to use the output of BERT to do the text classification, here is an example for getting the text representation

    ```
    # Assume `outputs` is the output from BERT model, having shape [batch_size, sequence_length, hidden_size]
    cls_embeddings = outputs[:, 0, :]
    ```
    
<br />

2. Splitting a Tensor into Batches

    In mini-batch training, you split your data into batches.
    ```
    data = torch.randn(100, 512)
    batch_size = 32

    for i in range(0, 100, batch_size):
        batch = data[i:i+batch_size]
    ```

<br />

3. Image Downscaling

    Downscale an image by taking every nth pixel.
    ```
    image = torch.randn(1, 3, 256, 256)
    downscaled = image[:, :, ::2, ::2]
    ```
    
    <details>
        <summary>>Some explaination(Click to expand)</summary>
    
        `1` - Represents the batch size. This tensor contains one image.
    
        `3` - Represents the number of channels (typically for RGB images, where 3 channels correspond to Red, Green, and Blue).
    
        `256` - Height of the image.
    
        `256` - Width of the image.
    
        `:` - The first `:` means we are taking all elements along the batch dimension. In this case, it's just one image.
    
        `:` - The second `:` means we are taking all channels of the image (R, G, B).
    
        `::2` - The first `::2` means we are taking every second pixel in the height dimension. It effectively halves the height of the image.
    
        `::2` - The first `::2` means we are taking every second pixel in the width dimension. It effectively halves the width of the image.
    
    </details>

<br />

4. Sequence Padding and Truncation in NLP

    Pad (or truncate) sequences to a fixed length for batching.
    ```
    max_length = 50
    sequence = torch.tensor([1, 2, 3, 4, 5])

    if len(sequence) < max_length:
        padded_sequence = torch.cat([sequence, torch.zeros(max_length - len(sequence))])
    else:
        padded_sequence = sequence[:max_length]

    ```
    
<br />

5. Selecting Specific Channels in an Image

    From an RGB image, extract only the Red channel.
    ```
    image = torch.randn(1, 3, 256, 256)
    red_channel = image[:, 0, :, :]
    ```

### Tensor Operations

#### Basic Computations

In [ ]:
a = torch.tensor([1, 2, 3], dtype=torch.float)
b = torch.tensor([4, 5, 6], dtype=torch.float)
print(f"Tensor a: {a}")
print(f"Tensor b: {b}")
print("="*40)

# Addition
# also we can use torch.add(a, b) or a+b
#your code

# Subtraction
# also we can use torch.sub(a, b) or a-b
#your code

# Multiplication (Element-wise)
# also we can use torch.mul(a, b) or a*b
#your code

# Division (Element-wise)
# also we can use torch.div(a, b)  or a/b
#your code


We can find that after all these computations, the value for `a` and `b` won't change.

In [ ]:
print(f"Tensor a: {a}")
print(f"Tensor b: {b}")

So this means that if we want to save the value after the computation, we always need to assign a new variable. Sometimes, we want to keep the changes in the original variable for memory and performance considerations. So, in PyTorch, we can use the in-place operation to do this.

In-place operations are a crucial aspect of PyTorch's tensor operations, especially when considering memory management and performance optimization.

In PyTorch, in-place operations are methods that have a `_` suffix, like `add_()`, `mul_()`, etc. These operations modify the original tensor directly and do not create a new one.

In [ ]:
# In-place addition
a.add_(b)
#your code

# In-place multiplication
#your code

In [ ]:
# In-place subtraction
a.sub_(b)
#your code

# In-place division
a.div_(b)
#your code

In [ ]:
print(f"Tensor b won't be affected: {b}")

#### Matrix Operations

In [ ]:
M = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float)
N = torch.tensor([[9, 8, 7], [6, 5, 4]], dtype=torch.float)
print(f"Matrix M: \n{M}")
print(f"Matrix N: \n{N}")
print("="*40)

# Matrix Multiplication
# also we can use  M.mm(N)
#your code

However, `torch.mm()` and `M.mm(N)` **only** works for **2D tensor**

We can use `torch.matmul()` or `M.matmul(N)` for higher dimension, the `matmul` support the not only **2D tensor**, but also **higher dimension**

In [ ]:
A_batch = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
B_batch = torch.tensor([[[2, 0], [0, 2]], [[1, 1], [1, 1]]])

#your code

# we can also use A_batch @ B_batch
#your code

In the above result:

The first batch `[[2, 4], [6, 8]]` of the result comes from the matrix multiplication of the first matrix of `A_batch` and `B_batch`, so `[[1, 2], [3, 4]] X [[2, 0], [0, 2]]`

The second batch `[[11, 11], [15, 15]]` of the result comes from the matrix multiplication of the second matrix of `A_batch` and `B_batch`, so `[[5, 6], [7, 8]] X [[1, 1], [1, 1]]]`

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Define two 2D vectors
A = np.array([2, 3])
B = np.array([-2, -3])

# Calculate the dot product
#your code

# Plot the vectors
plt.figure(figsize=(5, 5))
plt.quiver(0, 0, A[0], A[1], angles='xy', scale_units='xy', scale=1, color='blue', label='Vector A')
plt.quiver(0, 0, B[0], B[1], angles='xy', scale_units='xy', scale=1, color='red', label='Vector B')
plt.xlim(-4, 4)
plt.ylim(-4, 4)
plt.axhline(0, color='black',linewidth=0.5)
plt.axvline(0, color='black',linewidth=0.5)
plt.grid()
plt.legend()
plt.title("Dot Product of Vectors")
plt.text(0.5, 1, f"Dot Product: {dot_product}", fontsize=10, bbox=dict(facecolor='none', edgecolor='black'))
plt.show()


In [ ]:
# import numpy as np
# import matplotlib.pyplot as plt
# from mpl_toolkits.mplot3d import Axes3D

# # Define two vectors
# A = np.array([2, 3, 4])
# B = np.array([5, 6, 7])

# # Compute the cross product
# cross_product = np.cross(A, B)

# # Create a figure and 3D axis
# fig = plt.figure(figsize=(8, 8))
# ax = fig.add_subplot(111, projection='3d')

# # Plot the original vectors
# ax.quiver(0, 0, 0, A[0], A[1], A[2], color='blue', label='Vector A')
# ax.quiver(0, 0, 0, B[0], B[1], B[2], color='red', label='Vector B')

# # Plot the cross product vector
# ax.quiver(0, 0, 0, cross_product[0], cross_product[1], cross_product[2], color='green', label='Cross Product')

# # Set plot limits
# ax.set_xlim([0, max(A[0], B[0], cross_product[0])])
# ax.set_ylim([0, max(A[1], B[1], cross_product[1])])
# ax.set_zlim([0, max(A[2], B[2], cross_product[2])])

# # Set labels and title
# ax.set_xlabel('X')
# ax.set_ylabel('Y')
# ax.set_zlabel('Z')
# ax.set_title('Cross Product Visualization')

# # Show legend
# ax.legend()

# # Show the plot
# plt.show()


In [ ]:
a = torch.tensor([1, 2, 3], dtype=torch.float)
b = torch.tensor([4, 5, 6], dtype=torch.float)

print(f"Tensor a: {a}")
print(f"Tensor b: {b}")
print("="*40)

# Dot Product
# also we can use a.dot(b)
dot_product = torch.dot(a, b)
print(f"Dot Product of a and b: {dot_product}")
print("="*40)

# Norm (L2 norm by default)
# also we can use a.norm()
norm_result = torch.norm(a)
print(f"Norm of a (L2 by default): {norm_result}")

The inputs to `torch.dot` **must be 1D tensors**. And the **sizes** of the two tensors **must be the same**.

You can compute various norms (L1, L2, etc.) using `torch.norm`.

It can operate on multi-dimensional tensors. For a matrix, it will compute the Frobenius norm by default.

If you want to compute the norm across specific dimensions, you can specify them using the `dim` parameter.

If applied to a multi-dimensional tensor without specifying any dimensions, it will treat the tensor as a flattened 1D tensor and compute the norm accordingly.

Here is the official document for torch.norm

In [ ]:
help(torch.norm)

#### Conversions and Reshaping

In [ ]:
# Sample tensors for demonstration
a = torch.tensor([1, 2, 3], dtype=torch.float)

print(f"Tensor a: {a}")
print("="*40)

# Convert to Numpy
#your code

# Reshape
#your code

# View (similar to reshape)
#your code


 Both `view` and `reshape` return tensors that share the same underlying data with the original tensor, unless a data copy is made. This means that if you modify the original tensor, any tensors derived from it via `view` or `reshape` (when they don't involve a data copy) will also reflect those changes. Similarly, if you modify the reshaped or viewed tensor, the original tensor will change as well.

In [ ]:
print(f"Orignal Tensor a: {a}")
print("="*40)

# modify the original tensor
#your code

print("Modified original tensor:")
print(a)
print("="*40)
print("Viewed tensor:")
print(viewed_tensor)
print("="*40)
print("Reshaped tensor:")
print(reshaped_tensor)

In [ ]:
print(f"Orignal Tensor a: {a}")
print("="*40)

# modify the reshaped or viewed tensor
#your code

print("Modified original tensor:")
print(a)
print("="*40)
print("Viewed tensor:")
print(viewed_tensor)
print("="*40)
print("Reshaped tensor:")
print(reshaped_tensor)

In [ ]:
# Item (converts a 1-element tensor to a Python scalar)
one_element_tensor = torch.tensor([[[[5]]]])
scalar = one_element_tensor.item()
print(f"Scalar value from one_element_tensor: {scalar}")

`item` **only** works with tensor which **only has one element**.

#### Transpose

In [ ]:
M = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float)
#your code
print(f"Matrix M: \n{M}")
print("="*40)


print(f"Transposed Matrix of M: \n{transposed_matrix}")

We can also use the `transpose` and `permute` to do the transpose

In [ ]:
transposed_tensor = #your code  # Swapping dimension 0 with dimension 1
print(f"Transposed Matrix of M: \n{transposed_matrix}")

In [ ]:
#permuted_tensor = M.permute(1, 0)
#print(f"Transposed Matrix of M: \n{transposed_tensor}")

We can see the order of the parameter for `permute` and `transposed` is a different, the reason is:
 - transpose(dim0, dim1):
    - This method swaps two specified dimensions (dim0 and dim1).
    - For a 2D tensor (matrix), if you want to transpose it, you swap the rows and columns, so you use transpose(0, 1).

- permute(*dims):
    - This method allows for more general rearrangements of dimensions.
    - The argument to permute is a sequence of dimension indices.
    - For a 2D tensor, permute(1, 0) means you want the second dimension (index 1) to become the first, and the first dimension (index 0) to become the second.

Here is the comparison between these three transpose methods:

| Function   | Application              | Syntax                                     | Limitations                                                                                      | Use-Case                             |
|------------|--------------------------|--------------------------------------------|--------------------------------------------------------------------------------------------------|--------------------------------------|
| `t`        | Transposing matrices     | `torch.t(tensor)` or `tensor.t()`          | Only works for 2D tensors.                                                                       | Quick transposition of 2D matrices.   |
| `transpose`| Transposing dimensions   | `torch.transpose(tensor, dim0, dim1)`<br>or `tensor.transpose(dim0, dim1)`| Requires specifying two dimensions to swap.                                                     | Transposing any two specific dimensions. Useful for 2D tensors and beyond.   |
| `permute`  | Rearranging dimensions   | `tensor.permute(*dims)`                    | Requires specifying all dimensions in the new order.                                            | Rearranging order of all dimensions, especially useful for tensors with more than 2 dimensions. |


Example for `transpose` and `permute` in higher dimension tensor

In [ ]:
X = torch.arange(0,24).reshape(2, 3, 4)

print(f"The original 3D tensor:\n {X}")
print(f"\nThe shape of original 3D tensor:{X.shape}")
print("="*60)

# switch the 0th and 2nd dimensions
#your code

In [ ]:
print(f"The original 3D tensor:\n {X}")
print(f"\nThe shape of original 3D tensor:{X.shape}")
print("="*60)

# switch the 1st and 2nd dimensions
#your code

In [ ]:
print(f"The original 3D tensor:\n {X}")
print(f"\nThe shape of original 3D tensor:{X.shape}")
print("="*60)

# rearrange the order of dimensions
print("rearrange the order of dimensions using permute")
permuted_tensor = #your code
print(f"The transposed 3D tensor:\n {permuted_tensor}")
print(f"\nThe shape of transposed 3D tensor:{permuted_tensor.shape}")

In [ ]:
print(f"The original 3D tensor:\n {X}")
print(f"\nThe shape of original 3D tensor:{X.shape}")
print("="*60)

# rearrange the order of dimensions
print("rearrange the order of dimensions using permute")
permuted_tensor2 = #your code
print(f"The transposed 3D tensor:\n {permuted_tensor2}")
print(f"\nThe shape of transposed 3D tensor:{permuted_tensor2.shape}")